### ISSUE TITLE
trigger_joinhumanteam trigger_joinspectatorteam and trigger_joinzombieteam dont fire Outputs

### ISSUE THREAD

**Issue by xerox8521** [ZPSNMRiHIssues/zpsissues#177] opened 2015-03-28 18:16 UTC
All three triggers trigger_joinhumanteam trigger_joinspectator and trigger_joinzombieteam do not fire OnStartTouch altough its available in Hammer.

**Comment by jonnyboy0719** [comment] 2016-09-16 19:28
It's not a bug. Join triggers do not have any outputs, the FGD is just using the base trigger. This will be fixed on SDK 2013 version of FGD

**Closed as completed by jonnyboy0719** 2016-09-16 19:28 UTC
Labels: bug, wontfix, minor
