### ISSUE TITLE
zpa_town round does not end

### ISSUE THREAD

**Issue by xerox8521** [ZPSNMRiHIssues/zpsissues#87] opened 2013-05-19 12:01 UTC
On zpa_town if survivors could keep the entire 5-6 minutes the Capture Point and the Timer switches to "Over Time" the round does not end untill all survivors are killed and zombies take over the checkpoint which leads to a "Zombie win". Its almost every round if survivors can defend the Capture Point

Edit: Also Spectators in Lobby are frozen once the round started

**Comment by Smil3yRiley** [comment] 2013-05-20 16:40
Duplicate of https://github.com/ZPSNMRiHIssues/zpsissues/issues/7

**Closed as completed by Smil3yRiley** 2013-05-20 16:40 UTC
