### ISSUE TITLE
Steampipe Issues

### ISSUE THREAD

**Issue by xerox8521** [ZPSNMRiHIssues/zpsissues#122] opened 2013-08-04 02:12 UTC
Yesterday Steam required ZPS to convert to the Steampipe system. Now some sounds do not work anymore(water sounds for example). Random timeouts when playing the game or instant crash on full connect (when loading bar is about to reach 100%). No im not participant of the beta.

PS: Im unable to login into the Forums when i try to login i get this warning.

Warning: preg_replace() has been disabled for security reasons in /includes/functions.php on line 2761

**Comment by Smil3yRiley** [comment] 2013-08-04 17:13
Site's still under maintenance

As for SteamPipe we're trying to resolve it ASAP

**Comment by Smil3yRiley** [comment] 2013-08-18 21:30
Closing the ticket since Valve helped us with both the sound issue (you'll have to opt into the Steam Beta to get them working again, no word on when the Steam Beta client goes live) and the time outs (was caused by VAC)

**Closed as completed by Smil3yRiley** 2013-08-18 21:30 UTC
Labels: fixed
